
/****** Object:  Table [dbo].[HAYVAN_KAYIT_TURU]    Script Date: 08/20/2020 01:56:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HAYVAN_KAYIT_TURU](
	[SIRANO] [int] IDENTITY(1,1) NOT NULL,
	[KAYIT_TURU_ADU] [nvarchar](40) NOT NULL,
 CONSTRAINT [PK_HAYVAN_KAYIT_TURU] PRIMARY KEY CLUSTERED 
(
	[SIRANO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ILAC_TURU]    Script Date: 08/20/2020 01:56:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ILAC_TURU](
	[SIRANO] [int] IDENTITY(1,1) NOT NULL,
	[ILAC_ADI] [nvarchar](40) NOT NULL,
	[KULLANIM_TURU] [nvarchar](40) NULL,
 CONSTRAINT [PK_ILAC_TURU] PRIMARY KEY CLUSTERED 
(
	[SIRANO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[YEM_TURU]    Script Date: 08/20/2020 01:56:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[YEM_TURU](
	[SIRANO] [int] IDENTITY(1,1) NOT NULL,
	[YEM_TURU_ACIKLAMA] [nvarchar](40) NOT NULL,
 CONSTRAINT [PK_YEM_TURU] PRIMARY KEY CLUSTERED 
(
	[SIRANO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[YEM_KARISIM]    Script Date: 08/20/2020 01:56:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[YEM_KARISIM](
	[KARISIM_SIRANO] [int] IDENTITY(1,1) NOT NULL,
	[ACIKLAMA] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_YEM_KARISIM] PRIMARY KEY CLUSTERED 
(
	[KARISIM_SIRANO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VETERINER]    Script Date: 08/20/2020 01:56:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VETERINER](
	[SIRANO] [int] IDENTITY(1,1) NOT NULL,
	[VETERINER_ADI] [nvarchar](100) NOT NULL,
	[ADRES] [nvarchar](100) NULL,
	[TELEFON1] [nvarchar](20) NULL,
	[TELEFON2] [nvarchar](20) NULL,
	[EPOSTA] [nvarchar](200) NULL,
	[NOTLAR] [nvarchar](255) NULL,
 CONSTRAINT [PK_VETERINER] PRIMARY KEY CLUSTERED 
(
	[SIRANO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DOGUM_TURU]    Script Date: 08/20/2020 01:56:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DOGUM_TURU](
	[SIRANO] [int] IDENTITY(1,1) NOT NULL,
	[DOGUMTURU_ACIKLAMA] [nvarchar](40) NOT NULL,
 CONSTRAINT [PK_DOGUM_TURU] PRIMARY KEY CLUSTERED 
(
	[SIRANO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ASI_TURU]    Script Date: 08/20/2020 01:56:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ASI_TURU](
	[SIRANO] [int] IDENTITY(1,1) NOT NULL,
	[ASI_ADI] [nvarchar](40) NOT NULL,
 CONSTRAINT [PK_ASI_TURU] PRIMARY KEY CLUSTERED 
(
	[SIRANO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HAYVAN_CINSI]    Script Date: 08/20/2020 01:56:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HAYVAN_CINSI](
	[SIRANO] [int] IDENTITY(1,1) NOT NULL,
	[CINS_ADI] [nvarchar](40) NOT NULL,
 CONSTRAINT [PK_HAYVAN_CINSI] PRIMARY KEY CLUSTERED 
(
	[SIRANO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HAYVAN]    Script Date: 08/20/2020 01:56:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[HAYVAN](
	[KAYITNO] [int] IDENTITY(1,1) NOT NULL,
	[KAYIT_TARIHI] [datetime] NOT NULL,
	[DEVLET_NO] [nvarchar](40) NOT NULL,
	[BOYUN_NO] [nvarchar](40) NOT NULL,
	[KULAK_NO] [varchar](40) NOT NULL,
	[CINSIYETI] [int] NULL,
	[ANNE_KAYITNO] [int] NULL,
	[BABA_KAYITNO] [int] NULL,
	[HAYVANCINSI_SIRANO] [int] NOT NULL,
	[HAYVANKAYITTURU_SIRANO] [int] NULL,
	[DOGUM_TARIHI] [smalldatetime] NULL,
 CONSTRAINT [PK_HAYVAN] PRIMARY KEY CLUSTERED 
(
	[KAYITNO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[YEM_KARISIM_YEM_TURU]    Script Date: 08/20/2020 01:56:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[YEM_KARISIM_YEM_TURU](
	[KARISIM_SIRANO] [int] NOT NULL,
	[YEMTURU_SIRANO] [int] NOT NULL,
	[ORAN] [decimal](10, 2) NOT NULL,
 CONSTRAINT [PK_YEM_KARISIM_YEM_TURU] PRIMARY KEY CLUSTERED 
(
	[KARISIM_SIRANO] ASC,
	[YEMTURU_SIRANO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SAGLIK]    Script Date: 08/20/2020 01:56:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SAGLIK](
	[SIRANO] [int] NOT NULL,
	[HAYVAN_KAYITNO] [int] NOT NULL,
	[VETERINER_SIRANO] [int] NOT NULL,
	[ISLEM_TARIHI] [datetime] NOT NULL,
	[ISLEM_ACIKLAMA] [nvarchar](255) NULL,
	[NOTLAR] [nvarchar](4000) NULL,
 CONSTRAINT [PK_SAGLIK] PRIMARY KEY CLUSTERED 
(
	[SIRANO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HAYVAN_YEM_KARISIM_YEM_TURU]    Script Date: 08/20/2020 01:56:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HAYVAN_YEM_KARISIM_YEM_TURU](
	[KAYITNO] [int] NOT NULL,
	[HAYVAN_KAYITNO] [int] NOT NULL,
	[KARISIM_SIRANO] [int] NOT NULL,
	[YEM_SAATI] [datetime] NOT NULL,
	[ACIKLAMA] [nvarchar](100) NULL,
 CONSTRAINT [PK_HAYVAN_YEM_KARISIM_YEM_TURU] PRIMARY KEY CLUSTERED 
(
	[KAYITNO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HAYVAN_DOGUM_TURU]    Script Date: 08/20/2020 01:56:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HAYVAN_DOGUM_TURU](
	[HAYVAN_KAYITNO] [int] NOT NULL,
	[DOGUMTURU_SIRANO] [int] NOT NULL,
	[ACIKLAMA] [nvarchar](40) NULL,
	[VETERINER_SIRANO] [int] NULL,
 CONSTRAINT [PK_HAYVAN_DOGUM_TURU] PRIMARY KEY CLUSTERED 
(
	[HAYVAN_KAYITNO] ASC,
	[DOGUMTURU_SIRANO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SUT]    Script Date: 08/20/2020 01:56:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SUT](
	[SIRANO] [int] IDENTITY(1,1) NOT NULL,
	[HAYVAN_KAYITNO] [int] NULL,
	[SAGIM_TARIHI] [datetime] NOT NULL,
	[ALINAN_SUT] [decimal](10, 2) NULL,
 CONSTRAINT [PK_SUT] PRIMARY KEY CLUSTERED 
(
	[SIRANO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SAGLIK_ILAC]    Script Date: 08/20/2020 01:56:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SAGLIK_ILAC](
	[SAGLIK_IRANO] [int] NOT NULL,
	[ILACTURU_SIRANO] [int] NOT NULL,
	[ACIKLAMA] [nvarchar](50) NULL,
 CONSTRAINT [PK_SAGLIK_ILAC] PRIMARY KEY CLUSTERED 
(
	[SAGLIK_IRANO] ASC,
	[ILACTURU_SIRANO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SAGLIK_ASI_TURU]    Script Date: 08/20/2020 01:56:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SAGLIK_ASI_TURU](
	[SAGLIK_SIRANO] [int] NOT NULL,
	[ASITURU_SIRANO] [int] NOT NULL,
	[ACIKLAMA] [nvarchar](50) NULL,
 CONSTRAINT [PK_SAGLIK_ASI_TURU] PRIMARY KEY CLUSTERED 
(
	[SAGLIK_SIRANO] ASC,
	[ASITURU_SIRANO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Default [DEF_SUT_ALINAN_SUT]    Script Date: 08/20/2020 01:56:07 ******/
ALTER TABLE [dbo].[SUT] ADD  CONSTRAINT [DEF_SUT_ALINAN_SUT]  DEFAULT ((0)) FOR [ALINAN_SUT]
GO
/****** Object:  Default [DEF_YEM_KARISIM_YEM_TURU_ORAN]    Script Date: 08/20/2020 01:56:07 ******/
ALTER TABLE [dbo].[YEM_KARISIM_YEM_TURU] ADD  CONSTRAINT [DEF_YEM_KARISIM_YEM_TURU_ORAN]  DEFAULT ((0)) FOR [ORAN]
GO
/****** Object:  ForeignKey [HAYVAN_CINSI_HAYVAN]    Script Date: 08/20/2020 01:56:07 ******/
ALTER TABLE [dbo].[HAYVAN]  WITH CHECK ADD  CONSTRAINT [HAYVAN_CINSI_HAYVAN] FOREIGN KEY([HAYVANCINSI_SIRANO])
REFERENCES [dbo].[HAYVAN_CINSI] ([SIRANO])
GO
ALTER TABLE [dbo].[HAYVAN] CHECK CONSTRAINT [HAYVAN_CINSI_HAYVAN]
GO
/****** Object:  ForeignKey [HAYVAN_KAYIT_TURU_HAYVAN]    Script Date: 08/20/2020 01:56:07 ******/
ALTER TABLE [dbo].[HAYVAN]  WITH CHECK ADD  CONSTRAINT [HAYVAN_KAYIT_TURU_HAYVAN] FOREIGN KEY([HAYVANKAYITTURU_SIRANO])
REFERENCES [dbo].[HAYVAN_KAYIT_TURU] ([SIRANO])
GO
ALTER TABLE [dbo].[HAYVAN] CHECK CONSTRAINT [HAYVAN_KAYIT_TURU_HAYVAN]
GO
/****** Object:  ForeignKey [DOGUM_TURU_HAYVAN_DOGUM_TURU]    Script Date: 08/20/2020 01:56:07 ******/
ALTER TABLE [dbo].[HAYVAN_DOGUM_TURU]  WITH CHECK ADD  CONSTRAINT [DOGUM_TURU_HAYVAN_DOGUM_TURU] FOREIGN KEY([DOGUMTURU_SIRANO])
REFERENCES [dbo].[DOGUM_TURU] ([SIRANO])
GO
ALTER TABLE [dbo].[HAYVAN_DOGUM_TURU] CHECK CONSTRAINT [DOGUM_TURU_HAYVAN_DOGUM_TURU]
GO
/****** Object:  ForeignKey [HAYVAN_HAYVAN_DOGUM_TURU]    Script Date: 08/20/2020 01:56:07 ******/
ALTER TABLE [dbo].[HAYVAN_DOGUM_TURU]  WITH CHECK ADD  CONSTRAINT [HAYVAN_HAYVAN_DOGUM_TURU] FOREIGN KEY([HAYVAN_KAYITNO])
REFERENCES [dbo].[HAYVAN] ([KAYITNO])
GO
ALTER TABLE [dbo].[HAYVAN_DOGUM_TURU] CHECK CONSTRAINT [HAYVAN_HAYVAN_DOGUM_TURU]
GO
/****** Object:  ForeignKey [VETERINER_HAYVAN_DOGUM_TURU]    Script Date: 08/20/2020 01:56:07 ******/
ALTER TABLE [dbo].[HAYVAN_DOGUM_TURU]  WITH CHECK ADD  CONSTRAINT [VETERINER_HAYVAN_DOGUM_TURU] FOREIGN KEY([VETERINER_SIRANO])
REFERENCES [dbo].[VETERINER] ([SIRANO])
GO
ALTER TABLE [dbo].[HAYVAN_DOGUM_TURU] CHECK CONSTRAINT [VETERINER_HAYVAN_DOGUM_TURU]
GO
/****** Object:  ForeignKey [FK_HAYVAN_YEM_KARISIM_YEM_TURU_YEM_KARISIM]    Script Date: 08/20/2020 01:56:07 ******/
ALTER TABLE [dbo].[HAYVAN_YEM_KARISIM_YEM_TURU]  WITH CHECK ADD  CONSTRAINT [FK_HAYVAN_YEM_KARISIM_YEM_TURU_YEM_KARISIM] FOREIGN KEY([KARISIM_SIRANO])
REFERENCES [dbo].[YEM_KARISIM] ([KARISIM_SIRANO])
GO
ALTER TABLE [dbo].[HAYVAN_YEM_KARISIM_YEM_TURU] CHECK CONSTRAINT [FK_HAYVAN_YEM_KARISIM_YEM_TURU_YEM_KARISIM]
GO
/****** Object:  ForeignKey [HAYVAN_HAYVAN_YEM_KARISIM_YEM_TURU]    Script Date: 08/20/2020 01:56:07 ******/
ALTER TABLE [dbo].[HAYVAN_YEM_KARISIM_YEM_TURU]  WITH CHECK ADD  CONSTRAINT [HAYVAN_HAYVAN_YEM_KARISIM_YEM_TURU] FOREIGN KEY([HAYVAN_KAYITNO])
REFERENCES [dbo].[HAYVAN] ([KAYITNO])
GO
ALTER TABLE [dbo].[HAYVAN_YEM_KARISIM_YEM_TURU] CHECK CONSTRAINT [HAYVAN_HAYVAN_YEM_KARISIM_YEM_TURU]
GO
/****** Object:  ForeignKey [HAYVAN_SAGLIK]    Script Date: 08/20/2020 01:56:07 ******/
ALTER TABLE [dbo].[SAGLIK]  WITH CHECK ADD  CONSTRAINT [HAYVAN_SAGLIK] FOREIGN KEY([HAYVAN_KAYITNO])
REFERENCES [dbo].[HAYVAN] ([KAYITNO])
GO
ALTER TABLE [dbo].[SAGLIK] CHECK CONSTRAINT [HAYVAN_SAGLIK]
GO
/****** Object:  ForeignKey [VETERINER_SAGLIK]    Script Date: 08/20/2020 01:56:07 ******/
ALTER TABLE [dbo].[SAGLIK]  WITH CHECK ADD  CONSTRAINT [VETERINER_SAGLIK] FOREIGN KEY([VETERINER_SIRANO])
REFERENCES [dbo].[VETERINER] ([SIRANO])
GO
ALTER TABLE [dbo].[SAGLIK] CHECK CONSTRAINT [VETERINER_SAGLIK]
GO
/****** Object:  ForeignKey [ASI_TURU_SAGLIK_ASI_TURU]    Script Date: 08/20/2020 01:56:07 ******/
ALTER TABLE [dbo].[SAGLIK_ASI_TURU]  WITH CHECK ADD  CONSTRAINT [ASI_TURU_SAGLIK_ASI_TURU] FOREIGN KEY([ASITURU_SIRANO])
REFERENCES [dbo].[ASI_TURU] ([SIRANO])
GO
ALTER TABLE [dbo].[SAGLIK_ASI_TURU] CHECK CONSTRAINT [ASI_TURU_SAGLIK_ASI_TURU]
GO
/****** Object:  ForeignKey [SAGLIK_SAGLIK_ASI_TURU]    Script Date: 08/20/2020 01:56:07 ******/
ALTER TABLE [dbo].[SAGLIK_ASI_TURU]  WITH CHECK ADD  CONSTRAINT [SAGLIK_SAGLIK_ASI_TURU] FOREIGN KEY([SAGLIK_SIRANO])
REFERENCES [dbo].[SAGLIK] ([SIRANO])
GO
ALTER TABLE [dbo].[SAGLIK_ASI_TURU] CHECK CONSTRAINT [SAGLIK_SAGLIK_ASI_TURU]
GO
/****** Object:  ForeignKey [ILAC_TURU_SAGLIK_ILAC]    Script Date: 08/20/2020 01:56:07 ******/
ALTER TABLE [dbo].[SAGLIK_ILAC]  WITH CHECK ADD  CONSTRAINT [ILAC_TURU_SAGLIK_ILAC] FOREIGN KEY([ILACTURU_SIRANO])
REFERENCES [dbo].[ILAC_TURU] ([SIRANO])
GO
ALTER TABLE [dbo].[SAGLIK_ILAC] CHECK CONSTRAINT [ILAC_TURU_SAGLIK_ILAC]
GO
/****** Object:  ForeignKey [SAGLIK_SAGLIK_ILAC]    Script Date: 08/20/2020 01:56:07 ******/
ALTER TABLE [dbo].[SAGLIK_ILAC]  WITH CHECK ADD  CONSTRAINT [SAGLIK_SAGLIK_ILAC] FOREIGN KEY([SAGLIK_IRANO])
REFERENCES [dbo].[SAGLIK] ([SIRANO])
GO
ALTER TABLE [dbo].[SAGLIK_ILAC] CHECK CONSTRAINT [SAGLIK_SAGLIK_ILAC]
GO
/****** Object:  ForeignKey [HAYVAN_SUT]    Script Date: 08/20/2020 01:56:07 ******/
ALTER TABLE [dbo].[SUT]  WITH CHECK ADD  CONSTRAINT [HAYVAN_SUT] FOREIGN KEY([HAYVAN_KAYITNO])
REFERENCES [dbo].[HAYVAN] ([KAYITNO])
GO
ALTER TABLE [dbo].[SUT] CHECK CONSTRAINT [HAYVAN_SUT]
GO
/****** Object:  ForeignKey [YEM_KARISIM_YEM_KARISIM_YEM_TURU]    Script Date: 08/20/2020 01:56:07 ******/
ALTER TABLE [dbo].[YEM_KARISIM_YEM_TURU]  WITH CHECK ADD  CONSTRAINT [YEM_KARISIM_YEM_KARISIM_YEM_TURU] FOREIGN KEY([KARISIM_SIRANO])
REFERENCES [dbo].[YEM_KARISIM] ([KARISIM_SIRANO])
GO
ALTER TABLE [dbo].[YEM_KARISIM_YEM_TURU] CHECK CONSTRAINT [YEM_KARISIM_YEM_KARISIM_YEM_TURU]
GO
/****** Object:  ForeignKey [YEM_TURU_YEM_KARISIM_YEM_TURU]    Script Date: 08/20/2020 01:56:07 ******/
ALTER TABLE [dbo].[YEM_KARISIM_YEM_TURU]  WITH CHECK ADD  CONSTRAINT [YEM_TURU_YEM_KARISIM_YEM_TURU] FOREIGN KEY([YEMTURU_SIRANO])
REFERENCES [dbo].[YEM_TURU] ([SIRANO])
GO
ALTER TABLE [dbo].[YEM_KARISIM_YEM_TURU] CHECK CONSTRAINT [YEM_TURU_YEM_KARISIM_YEM_TURU]
GO
