//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYSLAU.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASI_TURU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASI_TURU()
        {
            this.SAGLIK_ASI_TURU = new HashSet<SAGLIK_ASI_TURU>();
        }

        public override string ToString()
        {
            return ASI_ADI;
        }
        public int SIRANO { get; set; }
        public string ASI_ADI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAGLIK_ASI_TURU> SAGLIK_ASI_TURU { get; set; }
    }
}
