//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYSLAU.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CYSEntities : DbContext
    {
        public CYSEntities()
            : base("name=CYSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ASI_TURU> ASI_TURU { get; set; }
        public virtual DbSet<DOGUM_TURU> DOGUM_TURU { get; set; }
        public virtual DbSet<HAYVAN> HAYVAN { get; set; }
        public virtual DbSet<HAYVAN_CINSI> HAYVAN_CINSI { get; set; }
        public virtual DbSet<HAYVAN_DOGUM_TURU> HAYVAN_DOGUM_TURU { get; set; }
        public virtual DbSet<HAYVAN_KAYIT_TURU> HAYVAN_KAYIT_TURU { get; set; }
        public virtual DbSet<HAYVAN_YEM_KARISIM_YEM_TURU> HAYVAN_YEM_KARISIM_YEM_TURU { get; set; }
        public virtual DbSet<ILAC_TURU> ILAC_TURU { get; set; }
        public virtual DbSet<SAGLIK> SAGLIK { get; set; }
        public virtual DbSet<SAGLIK_ASI_TURU> SAGLIK_ASI_TURU { get; set; }
        public virtual DbSet<SAGLIK_ILAC> SAGLIK_ILAC { get; set; }
        public virtual DbSet<SUT> SUT { get; set; }
        public virtual DbSet<VETERINER> VETERINER { get; set; }
        public virtual DbSet<YEM_KARISIM> YEM_KARISIM { get; set; }
        public virtual DbSet<YEM_KARISIM_YEM_TURU> YEM_KARISIM_YEM_TURU { get; set; }
        public virtual DbSet<YEM_TURU> YEM_TURU { get; set; }
    }
}
