//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYSLAU.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOGUM_TURU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOGUM_TURU()
        {
            this.HAYVAN_DOGUM_TURU = new HashSet<HAYVAN_DOGUM_TURU>();
        }

        public override string ToString()
        {
            return DOGUMTURU_ACIKLAMA;
        }
        public int SIRANO { get; set; }
        public string DOGUMTURU_ACIKLAMA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HAYVAN_DOGUM_TURU> HAYVAN_DOGUM_TURU { get; set; }
    }
}
