//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYSLAU.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAYVAN_DOGUM_TURU
    {
        public int HAYVAN_KAYITNO { get; set; }
        public int DOGUMTURU_SIRANO { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> VETERINER_SIRANO { get; set; }
    
        public virtual DOGUM_TURU DOGUM_TURU { get; set; }
        public virtual HAYVAN HAYVAN { get; set; }
        public virtual VETERINER VETERINER { get; set; }

        public override string ToString()
        {
            return ACIKLAMA;
        }
    }
}
