//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYSLAU.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAYVAN_YEM_KARISIM_YEM_TURU
    {
        public int KAYITNO { get; set; }
        public int HAYVAN_KAYITNO { get; set; }
        public int KARISIM_SIRANO { get; set; }
        public System.DateTime YEM_SAATI { get; set; }
        public string ACIKLAMA { get; set; }
    
        public virtual HAYVAN HAYVAN { get; set; }
        public virtual YEM_KARISIM YEM_KARISIM { get; set; }
    }
}
