//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYSLAU.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAYVAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HAYVAN()
        {
            this.HAYVAN_DOGUM_TURU = new HashSet<HAYVAN_DOGUM_TURU>();
            this.HAYVAN_YEM_KARISIM_YEM_TURU = new HashSet<HAYVAN_YEM_KARISIM_YEM_TURU>();
            this.SAGLIK = new HashSet<SAGLIK>();
            this.SUT = new HashSet<SUT>();
        }

        public override string ToString()
        {
            return "Devlet No:" + DEVLET_NO + " Boyun No:" + BOYUN_NO;
        }
        public int KAYITNO { get; set; }
        public System.DateTime KAYIT_TARIHI { get; set; }
        public string DEVLET_NO { get; set; }
        public string BOYUN_NO { get; set; }
        public string KULAK_NO { get; set; }
        public Nullable<int> CINSIYETI { get; set; }
        public Nullable<int> ANNE_KAYITNO { get; set; }
        public Nullable<int> BABA_KAYITNO { get; set; }
        public int HAYVANCINSI_SIRANO { get; set; }
        public Nullable<int> HAYVANKAYITTURU_SIRANO { get; set; }
        public Nullable<System.DateTime> DOGUM_TARIHI { get; set; }
    
        public virtual HAYVAN_CINSI HAYVAN_CINSI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HAYVAN_DOGUM_TURU> HAYVAN_DOGUM_TURU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HAYVAN_YEM_KARISIM_YEM_TURU> HAYVAN_YEM_KARISIM_YEM_TURU { get; set; }
        public virtual HAYVAN_KAYIT_TURU HAYVAN_KAYIT_TURU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAGLIK> SAGLIK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUT> SUT { get; set; }
    }
}
