//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYSLAU.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAYVAN_KAYIT_TURU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HAYVAN_KAYIT_TURU()
        {
            this.HAYVAN = new HashSet<HAYVAN>();
        }

        public override string ToString()
        {
            return KAYIT_TURU_ADU;
        }
        public int SIRANO { get; set; }
        public string KAYIT_TURU_ADU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HAYVAN> HAYVAN { get; set; }
    }
}
