//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYSLAU.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ILAC_TURU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ILAC_TURU()
        {
            this.SAGLIK_ILAC = new HashSet<SAGLIK_ILAC>();
        }

        public override string ToString()
        {
            return ILAC_ADI;
        }
        public int SIRANO { get; set; }
        public string ILAC_ADI { get; set; }
        public string KULLANIM_TURU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAGLIK_ILAC> SAGLIK_ILAC { get; set; }
    }
}
