//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYSLAU.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAGLIK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAGLIK()
        {
            this.SAGLIK_ASI_TURU = new HashSet<SAGLIK_ASI_TURU>();
            this.SAGLIK_ILAC = new HashSet<SAGLIK_ILAC>();
        }
    
        public int SIRANO { get; set; }
        public int HAYVAN_KAYITNO { get; set; }
        public int VETERINER_SIRANO { get; set; }
        public System.DateTime ISLEM_TARIHI { get; set; }
        public string ISLEM_ACIKLAMA { get; set; }
        public string NOTLAR { get; set; }
    
        public virtual HAYVAN HAYVAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAGLIK_ASI_TURU> SAGLIK_ASI_TURU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAGLIK_ILAC> SAGLIK_ILAC { get; set; }
        public virtual VETERINER VETERINER { get; set; }
    }
}
