//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYSLAU.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAGLIK_ILAC
    {
        public int SAGLIK_IRANO { get; set; }
        public int ILACTURU_SIRANO { get; set; }
        public string ACIKLAMA { get; set; }
    
        public virtual ILAC_TURU ILAC_TURU { get; set; }
        public virtual SAGLIK SAGLIK { get; set; }
    }
}
