//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYSLAU.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUT
    {
        public int SIRANO { get; set; }
        public Nullable<int> HAYVAN_KAYITNO { get; set; }
        public System.DateTime SAGIM_TARIHI { get; set; }
        public Nullable<decimal> ALINAN_SUT { get; set; }
    
        public virtual HAYVAN HAYVAN { get; set; }
    }
}
