//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYSLAU.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VETERINER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VETERINER()
        {
            this.HAYVAN_DOGUM_TURU = new HashSet<HAYVAN_DOGUM_TURU>();
            this.SAGLIK = new HashSet<SAGLIK>();
        }

        public override string ToString()
        {
            return VETERINER_ADI;
        }
        public int SIRANO { get; set; }
        public string VETERINER_ADI { get; set; }
        public string ADRES { get; set; }
        public string TELEFON1 { get; set; }
        public string TELEFON2 { get; set; }
        public string EPOSTA { get; set; }
        public string NOTLAR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HAYVAN_DOGUM_TURU> HAYVAN_DOGUM_TURU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAGLIK> SAGLIK { get; set; }
    }
}
