//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYSLAU.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class YEM_KARISIM_YEM_TURU
    {
        public int KARISIM_SIRANO { get; set; }
        public int YEMTURU_SIRANO { get; set; }
        public decimal ORAN { get; set; }
    
        public virtual YEM_KARISIM YEM_KARISIM { get; set; }
        public virtual YEM_TURU YEM_TURU { get; set; }
    }
}
